In [1]:
## James Schallert
## Machine Learning
## Homework 4

In [2]:
import numpy as np
import pandas as pd

In [3]:
X = np.array([
    [-2, 1, 4, 6, 5, 3, 6, 2],
    [9,3,2,-1,-4,-2,-4,-5],
    [0,7,-5,3,2,-3,4,6]
    ])


In [4]:
## Calculate the component means
means = X.mean(axis=1)

In [5]:
## Center the values of the matrix by subtracting the component mean from each component.
X = np.transpose(np.transpose(X)-means)

In [6]:
X

array([[-5.125, -2.125,  0.875,  2.875,  1.875, -0.125,  2.875, -1.125],
       [ 9.25 ,  3.25 ,  2.25 , -0.75 , -3.75 , -1.75 , -3.75 , -4.75 ],
       [-1.75 ,  5.25 , -6.75 ,  1.25 ,  0.25 , -4.75 ,  2.25 ,  4.25 ]])

In [7]:
## Find the covariance matrix by XX^T
C = np.matmul(X,np.transpose(X))

In [8]:
##Calculate the eiganvalues and eiganvectors of the covariance matrix.
eiganValues = np.linalg.eig(C)

In [9]:
##Find the largest eiganvalue and its corresponding eiganvector
biggestEiganValue = np.max(eiganValues[0])

biggestEiganIndex = np.where(eiganValues[0]==biggestEiganValue)

biggestEiganVector = eiganValues[1][:,biggestEiganIndex]

In [10]:
print(biggestEiganVector)

[[[ 0.37379192]]

 [[-0.84371817]]

 [[ 0.38525219]]]


In [11]:
## restoring the original X
originalX = np.array([
    [-2, 1, 4, 6, 5, 3, 6, 2],
    [9,3,2,-1,-4,-2,-4,-5],
    [0,7,-5,3,2,-3,4,6]
    ])

In [12]:
##First principal component is found by multiplying the original data by the unit vector of the largest eiganvalue.
firstPrincipalComponent = np.matmul(np.transpose(biggestEiganVector[:]),originalX)

In [13]:
##First principal component as a 1 dimensional matrix
print(firstPrincipalComponent)

[[[-8.34104738  0.53940272 -2.11852961  4.24222625  6.01433666
    1.65305553  7.15863295  7.27768782]]]


In [14]:
##First principal component as a 3dimensional matrix
firstPrincipalComponent3D = np.matmul(biggestEiganVector[:],firstPrincipalComponent)
firstPrincipalComponent3D

array([[[-3.1178161 ,  0.20162438, -0.79188925,  1.58570989,
          2.24811044,  0.6178988 ,  2.67583914,  2.72034089]],

       [[ 7.03749325, -0.45510388,  1.78744193, -3.57924337,
         -5.07440513, -1.39471299, -6.0398687 , -6.14031746]],

       [[-3.21340676,  0.20780608, -0.81616817,  1.63432694,
          2.31703636,  0.63684326,  2.75787901,  2.80374516]]])

In [15]:
leftovers = originalX - firstPrincipalComponent3D[0,:]

In [16]:
leftovers

array([[ 1.1178161 ,  0.79837562,  4.79188925,  4.41429011,  2.75188956,
         2.3821012 ,  3.32416086, -0.72034089],
       [12.1178161 ,  2.79837562,  2.79188925, -2.58570989, -6.24811044,
        -2.6178988 , -6.67583914, -7.72034089],
       [ 3.1178161 ,  6.79837562, -4.20811075,  1.41429011, -0.24811044,
        -3.6178988 ,  1.32416086,  3.27965911]])

In [17]:
def mypca(X,k):
    i=0
    leftovers = X
    principalComponents3D = []
    principalComponents = []
    PrincipalValues = []
    eiganVectors = []
    while i<k:
        means = leftovers.mean(axis=1)
        centeredLeftovers = np.transpose(np.transpose(leftovers)-means)

        C = np.matmul(centeredLeftovers,np.transpose(centeredLeftovers))

        eiganValues = np.linalg.eig(C)
        

        biggestEiganValue = np.max(eiganValues[0])
        PrincipalValues.append(biggestEiganValue)
        
        biggestEiganIndex = np.where(eiganValues[0]==biggestEiganValue)

        biggestEiganVector = eiganValues[1][:,biggestEiganIndex]
        eiganVectors.append(biggestEiganVector)
        
        nextPrincipalComponent = np.matmul(np.transpose(leftovers),biggestEiganVector[:,0])
        principalComponents.append(nextPrincipalComponent)
        
        nextPrincipalComponent3D = np.matmul(nextPrincipalComponent,biggestEiganVector)

        leftovers = leftovers - nextPrincipalComponent3D[:,:,0]

        principalComponents3D.append(np.transpose(nextPrincipalComponent3D))

        i+=1
    
  
    
    kDimensionalRepresentation = np.matmul(np.transpose(X),np.transpose(np.take(np.take(eiganVectors,0,axis=2),0,axis=2)))
    
    print('\n\nOptimal '+ str(k) + ' dimensional representation:')
    print(np.transpose(kDimensionalRepresentation))
    print('\nTop '+ str(k) + ' Principal Values:')
    print(np.transpose(PrincipalValues))
    print('\nTop '+ str(k) + ' Principal Components:')
    print(np.transpose(principalComponents))
    
    
    
    return [kDimensionalRepresentation,principalComponents, PrincipalValues]
    

In [18]:
X = np.array([
    [-2, 1, 4, 6, 5, 3, 6, 2],
    [9,3,2,-1,-4,-2,-4,-5],
    [0,7,-5,3,2,-3,4,6]
    ])

for k in range(1,4):
    mypca(X,k)




Optimal 1 dimensional representation:
[[-8.34104738  0.53940272 -2.11852961  4.24222625  6.01433666  1.65305553
   7.15863295  7.27768782]]

Top 1 Principal Values:
[201.73856252]

Top 1 Principal Components:
[[[-8.34104738]
  [ 0.53940272]
  [-2.11852961]
  [ 4.24222625]
  [ 6.01433666]
  [ 1.65305553]
  [ 7.15863295]
  [ 7.27768782]]]


Optimal 2 dimensional representation:
[[-8.34104738  0.53940272 -2.11852961  4.24222625  6.01433666  1.65305553
   7.15863295  7.27768782]
 [ 3.07960195  6.83029175 -5.2912228   0.5006905  -0.89099856 -4.23361802
   0.59710178  3.43903074]]

Top 2 Principal Values:
[201.73856252 113.25442962]

Top 2 Principal Components:
[[[-8.34104738  3.07960195]
  [ 0.53940272  6.83029175]
  [-2.11852961 -5.2912228 ]
  [ 4.24222625  0.5006905 ]
  [ 6.01433666 -0.89099856]
  [ 1.65305553 -4.23361802]
  [ 7.15863295  0.59710178]
  [ 7.27768782  3.43903074]]]


Optimal 3 dimensional representation:
[[-8.34104738  0.53940272 -2.11852961  4.24222625  6.01433666  1.653